# -*- coding: utf-8 -*-
"""Mad libs Python .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Q2tDq3dOv5owqsedY4-YblCloxSKz78

# **Mad libs Game in Python**
"""

# User Input
name = input('Enter a name: ')
programming_language = input('Enter a programming language (e.g: Python, Next.js, TypeScript): ')
mentor = input('Enter your mentor\'s name: ')

# New Story Created
print("\n Here is a brand new story based on your inputs!")
print(f"{name} was an imaginative soul with big dreams.")
print(f"One evening, while scrolling through the internet, {name} discovered the magic of {programming_language}.")
print(f"Determined to master it, {name} began a quest to find the best guidance.")
print(f"That’s when {name} met a wise and helpful mentor named {mentor}.")
print(f"Under {mentor}'s guidance, {name} learned not only to code, but to think like a real developer.")
print("And from that moment on, there was no turning back — the journey of a coding legend had just begun.")